// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXtDjaczg6uDix8dmmnOaBbZx6lV3PNo',
    appId: '1:948651783891:web:1dd1850cd47ce46a668626',
    messagingSenderId: '948651783891',
    projectId: 'fir-auth-f4a28',
    authDomain: 'fir-auth-f4a28.firebaseapp.com',
    storageBucket: 'fir-auth-f4a28.appspot.com',
    measurementId: 'G-TE3ZEHYJ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkMlpyBxpg9uS95ZdgiCWFBTz76J7XMc',
    appId: '1:948651783891:android:d39cbbfb6e031c30668626',
    messagingSenderId: '948651783891',
    projectId: 'fir-auth-f4a28',
    storageBucket: 'fir-auth-f4a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd8eGHUHt5PZ3bku8cxCl3dmqkgG09_Xg',
    appId: '1:948651783891:ios:fac63147bd3f2841668626',
    messagingSenderId: '948651783891',
    projectId: 'fir-auth-f4a28',
    storageBucket: 'fir-auth-f4a28.appspot.com',
    iosBundleId: 'com.example.firestoreAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd8eGHUHt5PZ3bku8cxCl3dmqkgG09_Xg',
    appId: '1:948651783891:ios:fac63147bd3f2841668626',
    messagingSenderId: '948651783891',
    projectId: 'fir-auth-f4a28',
    storageBucket: 'fir-auth-f4a28.appspot.com',
    iosBundleId: 'com.example.firestoreAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkXtDjaczg6uDix8dmmnOaBbZx6lV3PNo',
    appId: '1:948651783891:web:470e6e8734729acf668626',
    messagingSenderId: '948651783891',
    projectId: 'fir-auth-f4a28',
    authDomain: 'fir-auth-f4a28.firebaseapp.com',
    storageBucket: 'fir-auth-f4a28.appspot.com',
    measurementId: 'G-PNR1E1PJF3',
  );
}
